version : "3.8"
services:
  elasticsearch:
    image: elasticsearch:8.15.0 # stable version
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      #- "ES_JAVA_OPTS=-Xms512m -Xmx512m" # change if it is not enough
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  kibana: # ui for elasticsearch
    image: kibana:8.15.0 # stable version
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch

networks:
  elastic:
    driver: bridge